#!/usr/local/bin/perl
require './wireguard-lib.pl'; ReadParse(); assert_view_access(); assert_manage_access();
my$name=$in{'name'}||''; my($cfg,$ifc); if(length$name){error($text{'error_invalid_name'})if!valid_interface_name($name);($cfg,my$e)=parse_wireguard_config(conf_path($name));error(text('error_read',conf_path($name),$e))if!$cfg;$ifc=$cfg->{'interface'};}else{$ifc={'values'=>{},'meta'=>{}};}
sub ta{my($n,$v,$r)=@_;'<textarea name="'.html_escape($n).'" rows="'.$r.'" style="width:100%">'.html_escape($v||'').'</textarea>'}
ui_print_header(undef,length$name?text('interface_edit_title',$name):$text{'interface_add_title'},'',undef,1,1); print ui_form_start('save_interface.cgi','post'); print csrf_hidden(); print ui_hidden('old_name',$name)if length$name; print ui_hidden('config_digest',$cfg->{'digest'})if$cfg;
print ui_table_start($text{'interface_network_settings'},'width=100%',2); print ui_table_row($text{'interface_name'},length$name?'<b>'.html_escape($name).'</b>':ui_textbox('name','',20)); print ui_table_row($text{'interface_addresses'},ta('addresses',join("\n",get_section_values($ifc,'Address')),3)); print ui_table_row($text{'interface_listen_port'},ui_textbox('listen_port',get_section_value($ifc,'ListenPort')||'',10)); print ui_table_row($text{'interface_dns'},ta('dns',join("\n",get_section_values($ifc,'DNS')),2)); print ui_table_row($text{'interface_mtu'},ui_textbox('mtu',get_section_value($ifc,'MTU')||'',10)); print ui_table_row($text{'interface_table'},ui_textbox('table',get_section_value($ifc,'Table')||'',18)); print ui_table_row($text{'interface_fwmark'},ui_textbox('fwmark',get_section_value($ifc,'FwMark')||'',18)); print ui_table_row($text{'interface_saveconfig'},ui_select('saveconfig',get_section_value($ifc,'SaveConfig')||'',[['',$text{'none'}],['true',$text{'yes'}],['false',$text{'no'}]]).'<br><small>'.$text{'saveconfig_help'}.'</small>'); for my$h(qw(PreUp PostUp PreDown PostDown)){print ui_table_row($h,ta(lc$h,join("\n",get_section_values($ifc,$h)),3));} print ui_table_end();
print ui_table_start($text{'key_settings'},'width=100%',2); print ui_table_row($text{'interface_private_key'},html_escape(length($ifc->{'private_key'}||'')?$text{'key_saved'}:$text{'key_missing'})); print ui_table_row($text{'interface_private_key_new'},ui_password('private_key','',48).'<br><small>'.$text{'key_blank_keep'}.'</small>'); print ui_table_row($text{'interface_generate_key'},ui_checkbox('generate_key',1,$text{'interface_generate_key_help'},0)); print ui_table_row($text{'interface_public_key_import'},ui_textbox('public_key',$ifc->{'public_key_comment'}||'',52).'<br><small>'.$text{'key_public_ignored'}.'</small>'); print ui_table_end();
print ui_table_start($text{'interface_qr_settings'},'width=100%',2); print ui_table_row($text{'interface_client_endpoint'},ui_textbox('clientendpoint',get_meta_value($ifc,'clientendpoint')||'',48)); print ui_table_row($text{'interface_client_dns'},ui_textbox('clientdns',get_meta_value($ifc,'clientdns')||'',48)); print ui_table_row($text{'interface_client_allowed'},ui_textbox('clientallowedips',get_meta_value($ifc,'clientallowedips')||'',60).'<br><small>'.$text{'interface_client_allowed_help'}.'</small>'); print ui_table_row($text{'interface_client_mtu'},ui_textbox('clientmtu',get_meta_value($ifc,'clientmtu')||'',10)); print ui_table_end();
print '<div class="wg-save-actions"><button class="btn btn-success" name="save" value="1">'.$text{'save_only'}.'</button>'; if(length$name){print ' <button class="btn btn-warning" name="save_apply" value="1">'.$text{'save_apply_short'}.'</button> <button class="btn wg-orange" name="save_restart" value="1" onclick="return confirm(\''.js_escape($text{'confirm_restart'}).'\')">'.$text{'save_restart_short'}.'</button>';}else{print ' <button class="btn btn-success" name="save_start" value="1">'.$text{'save_start'}.'</button>';} print '</div></form><style>.wg-orange{background:#d97904!important;color:white!important}.wg-save-actions{margin:12px 0}</style>';
ui_print_footer(length$name?'edit_interface.cgi?name='.urlize($name):'index.cgi',length$name?text('interface_title',$name):$text{'index_title'});
