=head1 version-lib.pl

Release-version integration for runtime HTML generated by legacy helpers.

=cut

our $WIREGUARD_WEBMIN_VERSION = '0.2.0';
our $WG_VERSION_ORIGINAL_RUNTIME_POLL_HTML;

if (defined(&runtime_poll_html)) {
    $WG_VERSION_ORIGINAL_RUNTIME_POLL_HTML = \&runtime_poll_html;
    no warnings qw(redefine prototype);
    *runtime_poll_html = sub {
        my $html = $WG_VERSION_ORIGINAL_RUNTIME_POLL_HTML->(@_);
        $html =~ s/const API_BUILD='[^']*'/const API_BUILD='$WIREGUARD_WEBMIN_VERSION'/;
        return $html;
    };
}

1;
